//! Conformance harness: every fixture analyzed by `rcl_core::analyze_fixture`
//! must produce canonical JSON byte-identical to the committed golden
//! (generated by the TypeScript oracle). Mirrors the TS conformance test in
//! `packages/conformance-harness/test/conformance.test.ts`.

use std::fs;
use std::panic::{self, AssertUnwindSafe};
use std::path::{Path, PathBuf};

use rcl_core::{Kind, Range, Usage, analyzer, canonical};

fn repo_conformance_dir(sub: &str) -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("..")
        .join("..")
        .join("conformance")
        .join(sub)
}

fn collect_goldens(dir: &Path, out: &mut Vec<PathBuf>) {
    let Ok(entries) = fs::read_dir(dir) else {
        return;
    };
    let mut names: Vec<PathBuf> = entries.filter_map(|e| e.ok().map(|e| e.path())).collect();
    names.sort();
    for path in names {
        if path.is_dir() {
            collect_goldens(&path, out);
        } else if path.extension().is_some_and(|e| e == "json") {
            out.push(path);
        }
    }
}

/// Build the expected canonical string by re-serializing the golden's `usages`.
fn expected_from_golden(golden_path: &Path) -> String {
    let text = fs::read_to_string(golden_path).expect("read golden");
    let value: serde_json::Value = serde_json::from_str(&text).expect("parse golden json");
    let usages_json = value
        .get("usages")
        .and_then(serde_json::Value::as_array)
        .expect("golden.usages array");

    let mut usages: Vec<Usage> = usages_json
        .iter()
        .map(|u| Usage {
            kind: match u.get("kind").and_then(serde_json::Value::as_str) {
                Some("client") => Kind::Client,
                _ => Kind::Server,
            },
            tag_name: u
                .get("tagName")
                .and_then(serde_json::Value::as_str)
                .unwrap_or_default()
                .to_string(),
            source_file_path: u
                .get("sourceFilePath")
                .and_then(serde_json::Value::as_str)
                .unwrap_or_default()
                .to_string(),
            ranges: u
                .get("ranges")
                .and_then(serde_json::Value::as_array)
                .map(|rs| {
                    rs.iter()
                        .map(|r| Range {
                            start: u32::try_from(
                                r.get("start")
                                    .and_then(serde_json::Value::as_u64)
                                    .unwrap_or(0),
                            )
                            .unwrap_or(0),
                            end: u32::try_from(
                                r.get("end")
                                    .and_then(serde_json::Value::as_u64)
                                    .unwrap_or(0),
                            )
                            .unwrap_or(0),
                        })
                        .collect()
                })
                .unwrap_or_default(),
        })
        .collect();

    canonical::serialize_canonical(&mut usages)
}

/// Map `conformance/goldens/<rel>.json` -> `conformance/fixtures/<rel>`.
fn fixture_dir_for(golden: &Path, goldens_root: &Path, fixtures_root: &Path) -> PathBuf {
    let rel = golden
        .strip_prefix(goldens_root)
        .expect("golden under goldens root");
    let rel_no_ext = rel.with_extension("");
    fixtures_root.join(rel_no_ext)
}

#[test]
fn conformance_corpus_matches_oracle_goldens() {
    let goldens_root = repo_conformance_dir("goldens");
    let fixtures_root = repo_conformance_dir("fixtures");

    let mut goldens = Vec::new();
    collect_goldens(&goldens_root, &mut goldens);
    assert_ne!(goldens.len(), 0, "no goldens found under {goldens_root:?}");

    let mut passed = 0usize;
    let mut failures: Vec<String> = Vec::new();

    for golden in &goldens {
        let fixture_dir = fixture_dir_for(golden, &goldens_root, &fixtures_root);
        let name = golden
            .strip_prefix(&goldens_root)
            .unwrap_or(golden)
            .to_string_lossy()
            .replace('\\', "/");
        let expected = expected_from_golden(golden);

        let actual =
            panic::catch_unwind(AssertUnwindSafe(|| analyzer::analyze_fixture(&fixture_dir)));

        match actual {
            Ok(actual) if actual == expected => passed += 1,
            Ok(actual) => {
                let at = actual
                    .char_indices()
                    .zip(expected.char_indices())
                    .position(|((_, a), (_, b))| a != b)
                    .unwrap_or(actual.len().min(expected.len()));
                failures.push(format!(
                    "{name}: MISMATCH at ~{at}\n  expected: {}\n  actual:   {}",
                    &expected[at.saturating_sub(0)..expected.len().min(at + 80)],
                    &actual[at.saturating_sub(0)..actual.len().min(at + 80)],
                ));
            }
            Err(_) => failures.push(format!("{name}: PANIC (unimplemented or bug)")),
        }
    }

    let total = goldens.len();
    eprintln!("conformance: {passed}/{total} passing");
    assert_eq!(
        failures.len(),
        0,
        "{}/{} fixtures failed:\n{}",
        failures.len(),
        total,
        failures.join("\n")
    );
}
